### ISSUE TITLE
Meeting 19/12/2024

### ISSUE THREAD

**Issue by VOLEHUYDAT** [VOLEHUYDAT/CNPM-project16#12]

**Comment by TRANHOANGTHUONG** [comment]
Vẽ sơ đồ Use Case Diagram cho dự án, bao gồm:
Use case:
- Guest.
- Member.
- Staff.
- Admin.

Phân chia công việc:
- Guest: Gia Hưng, Quốc Tuấn.
- Member: Ngọc Tú,  Thiên Ân.
- Staff: Hoàng Thương.
- Admin: Huy Đạt.

Bổ sung mô tả tổng quát và up ảnh minh họa sơ đồ Use-case lên Document: Trung Hiếu.
