### ISSUE TITLE
Meeting 15/12/2024

### ISSUE THREAD

**Issue by VOLEHUYDAT** [VOLEHUYDAT/CNPM-project16#8]

**Comment by TRANHOANGTHUONG** [comment]
**Tìm thông tin về cách làm web:**
Tham khảo source code web bán hàng thực phẩm và giao diện của web concung.com , dùng ý tưởng tương tự để làm trang web bán sữa cho mẹ bầu và bé.

**Phân công việc cho các thành viên:**
- Task "Khách vãn lai": Quốc Tuấn, Gia Hưng
- Task "Thành viên": Hoàng Thương, Ngọc Tú
- Task "Nhân viên": Thiên Ân, Trung Hiếu
- Huy Đạt tổng kết, kiểm tra chức năng của các task.
